<?php

use Illuminate\Database\Seeder;

class nrcTownshipsSeeder extends Seeder
{
    use CommandOutput;
    /**
     * Run the database seeds.
     *
     * @return void
     */
    protected $states_with_townships = [
        1 => [ //ကချင်ပြည်နယ်
            ['township_abbreviation' => 'ဗမန', 'township_name' => 'ဗန်းမော်မြို့နယ်'],
            ['township_abbreviation' => 'ခဖန', 'township_name' => 'ချီဖွေမြို့နယ်'],
            ['township_abbreviation' => 'ဒဖယ', 'township_name' => 'ဒေါ့ဖုန်းယန်'],
            ['township_abbreviation' => 'ဟပန', 'township_name' => 'ဟိုပင်မြို့နယ်'],
            ['township_abbreviation' => 'ဆလန', 'township_name' => 'ဆော့လော်မြို့နယ်'],
            ['township_abbreviation' => 'အဂယ', 'township_name' => 'အင်ဂျင်းယန်မြို့နယ်'],
            ['township_abbreviation' => 'ကမန', 'township_name' => 'ကာမိုင်းမြို့နယ်'],
            ['township_abbreviation' => 'ခဘဒ', 'township_name' => 'ခေါင်လန်ဖူးမြို့နယ်'],
            ['township_abbreviation' => 'လဂန', 'township_name' => 'လွယ်ဂျယ်မြို့နယ်'],
            ['township_abbreviation' => 'မခဘ', 'township_name' => 'မချမ်းဘောမြို့နယ်'],
            ['township_abbreviation' => 'မစန', 'township_name' => 'မန်စီမြို့နယ်'],
            ['township_abbreviation' => 'မကန', 'township_name' => 'မိုးကောင်းမြို့နယ်'],
            ['township_abbreviation' => 'မညန', 'township_name' => 'မိုးညှင်းမြို့နယ်'],
            ['township_abbreviation' => 'မမန', 'township_name' => 'မိုးမောက်မြို့နယ်'],
            ['township_abbreviation' => 'မကန', 'township_name' => 'မြစ်ကြီးနားမြို့နယ်'],
            ['township_abbreviation' => 'မလတ', 'township_name' => 'မြို့လှမြို့နယ်'],
            ['township_abbreviation' => 'နမန', 'township_name' => 'နောင်မွန်းမြို့နယ်'],
            ['township_abbreviation' => 'ပနဒ', 'township_name' => 'ပန်နန်းဒင်မြို့နယ်'],
            ['township_abbreviation' => 'ကမန', 'township_name' => 'ဖားကန့်မြို့နယ်'],
            ['township_abbreviation' => 'ပတအ', 'township_name' => 'ပူတာအိုမြို့နယ်'],
            ['township_abbreviation' => 'ဆဒန', 'township_name' => 'ဆဒုံးမြို့နယ်'],
            ['township_abbreviation' => 'ရဗရ', 'township_name' => 'ရှင်ဗွေယန်မြို့နယ်'],
            ['township_abbreviation' => 'ရကန', 'township_name' => 'ရွှေကူမြို့နယ်'],
            ['township_abbreviation' => 'ဆဘန', 'township_name' => 'ဆင်ဘိုမြို့နယ်'],
            ['township_abbreviation' => 'ဆပဘ', 'township_name' => 'ဆွမ်ပရာဘွမ်မြို့နယ်'],
            ['township_abbreviation' => 'တနန', 'township_name' => 'တနိုင်းမြို့နယ်'],
            ['township_abbreviation' => 'ဝမန', 'township_name' => 'ဝိုင်းမော်မြို့နယ်'],
        ],
        2 => [ //ကယားပြည်နယ်
            ['township_abbreviation' => 'လကန', 'township_name' => 'လွိုင်ကော်မြို့နယ်'],
            ['township_abbreviation' => 'ဒမဆ', 'township_name' => 'ဒီမော့ဆိုမြို့နယ်'],
            ['township_abbreviation' => 'ဖရဆ', 'township_name' => 'ဖရူဆိုမြို့နယ်'],
            ['township_abbreviation' => 'ရတန', 'township_name' => 'ရှားတောမြို့နယ်'],
            ['township_abbreviation' => 'ဘလခ', 'township_name' => 'ဘောလခဲမြို့နယ်'],
            ['township_abbreviation' => 'ဖဆန', 'township_name' => 'ဖားဆောင်းမြို့နယ်'],
            ['township_abbreviation' => 'မစန', 'township_name' => 'မယ်စဲ့မြို့နယ်']
        ],
        3 => [ //ကရင်ပြည်နယ်
            ['township_abbreviation' => 'ဘအန', 'township_name' => 'ဘားအံမြို့နယ်'],
            ['township_abbreviation' => 'မဝတ', 'township_name' => 'မြဝတီမြို့နယ်'],
            ['township_abbreviation' => 'ကကရ', 'township_name' => 'ကော့ကရိတ်မြို့နယ်'],
            ['township_abbreviation' => 'ဖပန', 'township_name' => 'ဖာပွန်မြို့နယ်'],
            ['township_abbreviation' => 'ကဆက', 'township_name' => 'ကြာအင်းဆိတ်ကြီးမြို့နယ်'],
            ['township_abbreviation' => 'လဘန', 'township_name' => 'လှိုင်းဘွဲ့မြို့နယ်'],
            ['township_abbreviation' => 'သတန', 'township_name' => 'သံတောင်မြို့နယ်']
        ],
        4 => [ //ချင်းပြည်နယ်
            ['township_abbreviation' => 'ဟခန', 'township_name' => 'ဟားခါးမြို့နယ်'],
            ['township_abbreviation' => 'ဖလန', 'township_name' => 'ဖလမ်းမြို့နယ်'],
            ['township_abbreviation' => 'မတန', 'township_name' => 'မင်းတပ်မြို့နယ်'],
            ['township_abbreviation' => 'ပလဝ', 'township_name' => 'ပလက်ဝမြို့နယ်'],
            ['township_abbreviation' => 'တတန', 'township_name' => 'တီးတိန်မြို့နယ်'],
            ['township_abbreviation' => 'မတပ', 'township_name' => 'မတူပီမြို့နယ်'],
            ['township_abbreviation' => 'တဇန', 'township_name' => 'တွန်းဇန်မြို့နယ်'],
            ['township_abbreviation' => 'ထတလ', 'township_name' => 'ထန်တလန်မြို့နယ်'],
            ['township_abbreviation' => 'ကပလ', 'township_name' => 'ကန်ပက်လက်မြို့နယ်']
        ],
        5 => [ // စစ်ကိုင်းတိုင်းဒေသကြီး
            ['township_abbreviation' => 'အရတ', 'township_name' => 'အရာတော်မြို့နယ်'],
            ['township_abbreviation' => 'ဗမန', 'township_name' => 'ဗန်းမောက်မြို့နယ်'],
            ['township_abbreviation' => 'ဘတလ', 'township_name' => 'ဘုတလင်မြို့နယ်'],
            ['township_abbreviation' => 'ခဥတ', 'township_name' => 'ချောင်းဦးမြို့နယ်'],
            ['township_abbreviation' => 'ဒပယ', 'township_name' => 'ဒီပဲယင်းမြို့နယ်'],
            ['township_abbreviation' => 'ခတန', 'township_name' => 'ခန္တီးမြို့နယ်'],
            ['township_abbreviation' => 'ဟမလ', 'township_name' => 'ဟုမ္မလင်းမြို့နယ်'],
            ['township_abbreviation' => 'အတန', 'township_name' => 'အင်းတော်မြို့နယ်'],
            ['township_abbreviation' => 'ကလထ', 'township_name' => 'ကလေးမြို့နယ်'],
            ['township_abbreviation' => 'ကလဝ', 'township_name' => 'ကလေးဝမြို့နယ်'],
            ['township_abbreviation' => 'ကဘလ', 'township_name' => 'ကန့်ဘလူမြို့နယ်'],
            ['township_abbreviation' => 'ကနန', 'township_name' => 'ကနီမြို့နယ်'],
            ['township_abbreviation' => 'ကသန', 'township_name' => 'ကသာမြို့နယ်'],
            ['township_abbreviation' => 'ကလတ', 'township_name' => 'ကောလင်းမြို့နယ်'],
            ['township_abbreviation' => 'ခဥန', 'township_name' => 'ခင်ဦးမြို့နယ်'],
            ['township_abbreviation' => 'ကလန', 'township_name' => 'ကျွန်းလှမြို့နယ်'],
            ['township_abbreviation' => 'လဟန', 'township_name' => 'လဟယ်မြို့နယ်'],
            ['township_abbreviation' => 'လရန', 'township_name' => 'လေရှီးမြို့နယ်'],
            ['township_abbreviation' => 'မလန', 'township_name' => 'မော်လိုက်မြို့နယ်'],
            ['township_abbreviation' => 'မကန', 'township_name' => 'မင်းကင်းမြို့နယ်'],
            ['township_abbreviation' => 'မရန', 'township_name' => 'မုံရွာမြို့နယ်'],
            ['township_abbreviation' => 'မမန', 'township_name' => 'မြောင်မြို့နယ်'],
            ['township_abbreviation' => 'မမတ', 'township_name' => 'မြင်းမူမြို့နယ်'],
            ['township_abbreviation' => 'နယန', 'township_name' => 'နန်းယွန်းမြို့နယ်'],
            ['township_abbreviation' => 'ပလန', 'township_name' => 'ပုလဲမြို့နယ်'],
            ['township_abbreviation' => 'ဖပန', 'township_name' => 'ဖောင်းပြင်မြို့နယ်'],
            ['township_abbreviation' => 'ပလဘ', 'township_name' => 'ပင်လည်ဘူးမြို့နယ်'],
            ['township_abbreviation' => 'စကန', 'township_name' => 'စစ်ကိုင်းမြို့နယ်'],
            ['township_abbreviation' => 'ဆလက', 'township_name' => 'ဆားလင်းကြီးမြို့နယ်'],
            ['township_abbreviation' => 'ရဘန', 'township_name' => 'ရွှေဘိုမြို့နယ်'],
            ['township_abbreviation' => 'တမန', 'township_name' => 'တမူးမြို့နယ်'],
            ['township_abbreviation' => 'တဆန', 'township_name' => 'တန့်ဆည်မြို့နယ်'],
            ['township_abbreviation' => 'ထခန', 'township_name' => 'ထီးချိုင်မြို့နယ်'],
            ['township_abbreviation' => 'ဝလန', 'township_name' => 'ဝက်လက်မြို့နယ်'],
            ['township_abbreviation' => 'ဝသန', 'township_name' => 'ဝန်းသိုမြို့နယ်'],
            ['township_abbreviation' => 'ရဥန', 'township_name' => 'ရေဦးမြို့နယ်'],
            ['township_abbreviation' => 'ယမပ', 'township_name' => 'ယင်းမာပင်မြို့နယ်'],
        ],
        6 => [// တနင်္သာရီတိုင်း
            ['township_abbreviation' => 'ထဝန', 'township_name' => 'ထားဝယ်မြို့နယ်'],
            ['township_abbreviation' => 'မမန', 'township_name' => 'မြိတ်မြို့နယ်'],
            ['township_abbreviation' => 'ကသန', 'township_name' => 'ကော့သောင်းမြို့နယ်'],
            ['township_abbreviation' => 'လလန', 'township_name' => 'လောင်းလုံးမြို့နယ်'],
            ['township_abbreviation' => 'သရခ', 'township_name' => 'သရက်ချောင်းမြို့နယ်'],
            ['township_abbreviation' => 'ရဖန', 'township_name' => 'ရေဖြူမြို့နယ်'],
            ['township_abbreviation' => 'ကစန', 'township_name' => 'ကျွန်းစုမြို့နယ်'],
            ['township_abbreviation' => 'ပလန', 'township_name' => 'ပုလောမြို့နယ်'],
            ['township_abbreviation' => 'ဘပန', 'township_name' => 'ဘုတ်ပြင်းမြို့နယ်'],
        ],
        7 => [ // 'ပဲခူးတိုင်း'
            ['township_abbreviation' => 'ပခန', 'township_name' => 'ပဲခူးမြို့နယ်'],
            ['township_abbreviation' => 'ကတခ', 'township_name' => 'ကျောက်တံခါးမြို့နယ်'],
            ['township_abbreviation' => 'ဇကန', 'township_name' => 'ဇီးကုန်းမြို့နယ်'],
            ['township_abbreviation' => 'ညလပ', 'township_name' => 'ညောင်လေးပင်မြို့နယ်'],
            ['township_abbreviation' => 'တငန', 'township_name' => 'တောင်ငူမြို့နယ်'],
            ['township_abbreviation' => 'နတလ', 'township_name' => 'နတ္တလင်းမြို့နယ်'],
            ['township_abbreviation' => 'ကဝန', 'township_name' => 'ကဝမြို့နယ်'],
            ['township_abbreviation' => 'ပမန', 'township_name' => 'ပြည်မြို့နယ်'],
            ['township_abbreviation' => 'ပတန', 'township_name' => 'ပေါင်းတည်မြို့နယ်'],
            ['township_abbreviation' => 'ဖမန', 'township_name' => 'ဖြူးမြို့နယ်'],
            ['township_abbreviation' => 'မလန', 'township_name' => 'မင်းလှမြို့နယ်'],
            ['township_abbreviation' => 'ရတရ', 'township_name' => 'ရေတာရှည်မြို့နယ်'],
            ['township_abbreviation' => 'လပတ', 'township_name' => 'လက်ပံတန်းမြို့နယ်'],
            ['township_abbreviation' => 'ဝမန', 'township_name' => 'ဝေါမြို့နယ်'],
            ['township_abbreviation' => 'သဝတ', 'township_name' => 'သာယာဝတီမြို့နယ်'],
            ['township_abbreviation' => 'သကန', 'township_name' => 'သဲကုန်းမြို့နယ်'],
            ['township_abbreviation' => 'အဖန', 'township_name' => 'အုတ်ဖိုမြို့နယ်'],
            ['township_abbreviation' => 'မညန', 'township_name' => 'မိုးညိုမြို့နယ်'],
            ['township_abbreviation' => 'ပခန', 'township_name' => 'ပေါက်ခေါင်းမြို့နယ်'],
            ['township_abbreviation' => 'ဒဥန', 'township_name' => 'ဒိုက်ဦးမြို့နယ်'],
            ['township_abbreviation' => 'သနပ', 'township_name' => 'သနပ်ပင်မြို့နယ်'],
            ['township_abbreviation' => 'ထတပ', 'township_name' => 'ထန်းတပင်မြို့နယ်'],
            ['township_abbreviation' => 'အတန', 'township_name' => 'အုတ်တွင်းမြို့နယ်'],
            ['township_abbreviation' => 'ကကန', 'township_name' => 'ကျောက်ကြီးမြို့နယ်'],
            ['township_abbreviation' => 'ရကန', 'township_name' => 'ရွှေကျင်မြို့နယ်'],
            ['township_abbreviation' => 'ကပက', 'township_name' => 'ကြို့ပင်ကောက်မြို့နယ်'],
            ['township_abbreviation' => 'ရတန', 'township_name' => 'ရွှေတောင်မြို့နယ်'],
            ['township_abbreviation' => 'ပတန', 'township_name' => 'ပန်တောင်းမြို့နယ်']
        ],
        8 => [ // မကွေးတိုင်း
            ['township_abbreviation' => 'မကန', 'township_name' => 'မကွေးမြို့နယ်'],
            ['township_abbreviation' => 'ခမန', 'township_name' => 'ချောက်မြို့နယ်'],
            ['township_abbreviation' => 'ပလန', 'township_name' => ''],
            ['township_abbreviation' => 'သရန', 'township_name' => 'သရက်မြို့နယ်'],
            ['township_abbreviation' => 'ဂဂန', 'township_name' => 'ဂန့်ဂေါမြို့နယ်'],
            ['township_abbreviation' => 'နမန', 'township_name' => 'နတ်မောက်မြို့နယ်'],
            ['township_abbreviation' => 'မသန', 'township_name' => 'မြို့သစ်မြို့နယ်'],
            ['township_abbreviation' => 'ရနခ', 'township_name' => 'ရေနံချောင်းမြို့နယ်'],
            ['township_abbreviation' => 'တတက', 'township_name' => 'တောင်တွင်းကြီးမြို့နယ်'],
            ['township_abbreviation' => 'မဘန', 'township_name' => 'မင်းဘူးမြို့နယ်'],
            ['township_abbreviation' => 'ပဖန', 'township_name' => 'ပွင့်ဖြူမြို့နယ်'],
            ['township_abbreviation' => 'စလန', 'township_name' => 'စလင်းမြို့နယ်'],
            ['township_abbreviation' => 'ငဖန', 'township_name' => 'ငဖဲမြို့နယ်'],
            ['township_abbreviation' => 'စတရ', 'township_name' => 'စေတုတ္တရာမြို့နယ်'],
            ['township_abbreviation' => 'ဆဖန', 'township_name' => 'ဆိပ်ဖြူမြို့နယ်'],
            ['township_abbreviation' => 'ရစက', 'township_name' => 'ရေစကြိုမြို့နယ်'],
            ['township_abbreviation' => 'မမန', 'township_name' => 'မြိုင်မြို့နယ်'],
            ['township_abbreviation' => 'ပမန', 'township_name' => 'ပေါက်မြို့နယ်'],
            ['township_abbreviation' => 'ထလန', 'township_name' => 'ထီးလင်းမြို့နယ်'],
            ['township_abbreviation' => 'ဆမန', 'township_name' => 'ဆောမြို့နယ်'],
            ['township_abbreviation' => 'အလန', 'township_name' => 'အောင်လံမြို့နယ်'],
            ['township_abbreviation' => 'ဆပဝ', 'township_name' => 'ဆင်ပေါင်ဝဲမြို့နယ်'],
            ['township_abbreviation' => 'မတန', 'township_name' => 'မင်းတုန်းမြို့နယ်'],
            ['township_abbreviation' => 'မလန', 'township_name' => 'မင်းလှမြို့နယ်'],
            ['township_abbreviation' => 'ကမန', 'township_name' => 'ကံမမြို့နယ်']
        ],
        9 => [ //မန္တလေးတိုင်း
            ['township_abbreviation' => 'ကဆန', 'township_name' => 'ကျောက်ဆည်'],
            ['township_abbreviation' => 'မထလ', 'township_name' => 'မိတ္ထီလာမြို့နယ်'],
            ['township_abbreviation' => 'မခန', 'township_name' => 'မြင်းခြံမြို့နယ်'],
            ['township_abbreviation' => 'ညဥန', 'township_name' => 'ညောင်ဦးမြို့နယ်'],
            ['township_abbreviation' => 'ပဥန', 'township_name' => ''],
            ['township_abbreviation' => 'ရမသ', 'township_name' => 'ရမည်းသင်းမြို့နယ်'],
            ['township_abbreviation' => 'အမဖ', 'township_name' => ''],
            ['township_abbreviation' => 'ခအဇ', 'township_name' => ''],
            ['township_abbreviation' => 'ပကခ', 'township_name' => 'ပြည်ကြီးတံခွန်မြို့နယ်'],
            ['township_abbreviation' => 'အမရ', 'township_name' => 'အမရပူရမြို့နယ်'],
            ['township_abbreviation' => 'ပဥလ', 'township_name' => 'ပြင်ဦးလွင်မြို့နယ်'],
            ['township_abbreviation' => 'ခအဇ', 'township_name' => ''],
            ['township_abbreviation' => 'ပသက', 'township_name' => 'ပုသိမ်ကြီးမြို့နယ်'],
            ['township_abbreviation' => 'မတရ', 'township_name' => 'မတ္တရာမြို့နယ်'],
            ['township_abbreviation' => 'စကန', 'township_name' => 'စဉ့်ကူးမြို့နယ်'],
            ['township_abbreviation' => 'မကန', 'township_name' => 'မိုးကုတ်မြို့နယ်'],
            ['township_abbreviation' => 'သပက', 'township_name' => 'သပိတ်ကျင်းမြို့နယ်'],
            ['township_abbreviation' => 'စကန', 'township_name' => 'စဉ့်ကိုင်မြို့နယ်'],
            ['township_abbreviation' => 'မသန', 'township_name' => 'မြစ်သားမြို့နယ်'],
            ['township_abbreviation' => 'တတဥ', 'township_name' => 'တံတားဦးမြို့နယ်'],
            ['township_abbreviation' => 'တသန', 'township_name' => 'တောင်သာမြို့နယ်'],
            ['township_abbreviation' => 'နထက', 'township_name' => 'နွားထိုးကြီးမြို့နယ်'],
            ['township_abbreviation' => 'ကပတ', 'township_name' => 'ကျောက်ပန်းတောင်းမြို့နယ်'],
            ['township_abbreviation' => 'ငဇန', 'township_name' => 'ငါန်းဇွန်းမြို့နယ်'],
            ['township_abbreviation' => 'ပဘန', 'township_name' => 'ပျော်ဘွယ်မြို့နယ်'],
            ['township_abbreviation' => 'မလန', 'township_name' => 'မလှိုင်မြို့နယ်'],
            ['township_abbreviation' => 'သစန', 'township_name' => 'သာစည်မြို့နယ်'],
            ['township_abbreviation' => 'ဝတန', 'township_name' => 'ဝမ်းတွင်းမြို့နယ်']
        ],
        10 => [ //မွန်ပြည်နယ်
            ['township_abbreviation' =>'သထန','township_name' => 'သထုံမြို့နယ်'],
            ['township_abbreviation' =>'မလမ', 'township_name' => 'မော်လမြိုင်မြို့နယ်'],
            ['township_abbreviation' =>'ကမရ', 'township_name' => 'ကျိုက်မရောမြို့နယ်'],
            ['township_abbreviation' =>'ကထန', 'township_name' => 'ကျိုက်ထိုမြို့နယ်'],
            ['township_abbreviation' => 'ခဆန', 'township_name' => 'ချောင်းဆုံမြို့နယ်'],
            ['township_abbreviation' => 'ပမန', 'township_name' => 'ပေါင်မြို့နယ်'],
            ['township_abbreviation' => 'ဘလန', 'township_name' => 'ဘီးလင်းမြို့နယ်'],
            ['township_abbreviation' => 'မဒန', 'township_name' => 'မုဒုံမြို့နယ်'],
            ['township_abbreviation' => 'ရမန', 'township_name' => 'ရေးမြို့နယ်'],
            ['township_abbreviation' =>'သဖရ', 'township_name' => 'သံဖြူဇရပ်မြို့နယ်']
        ],
        11 => [ //ရခိုင်ပြည်နယ်
            ['township_abbreviation' => 'အမန', 'township_name' => 'အမ်းမြို့နယ်'],
            ['township_abbreviation' => 'ဂမန', 'township_name' => 'ဂွမြို့နယ်'],
            ['township_abbreviation' => 'ကတန', 'township_name' => 'ကျောက်တော်မြို့နယ်'],
            ['township_abbreviation' => 'မပန', 'township_name' => 'မင်းပြားမြို့နယ်'],
            ['township_abbreviation' => 'မဥန', 'township_name' => 'မြောက်ဦးမြို့နယ်'],
            ['township_abbreviation' => 'မအန', 'township_name' => 'မာန်အောင်မြို့နယ်'],
            ['township_abbreviation' =>'မပန', 'township_name' => 'မြေပုံမြို့နယ်'],
            ['township_abbreviation' => 'ပတန', 'township_name' => 'ပေါက်တောမြို့နယ်'],
            ['township_abbreviation' => 'ရဗန', 'township_name' => 'ရမ်းဗြဲမြို့နယ်'],
            ['township_abbreviation' => 'ရသန', 'township_name' => 'ရသေ့တောင်မြို့နယ်'],
            ['township_abbreviation' => 'တကန', 'township_name' => 'တောင်ကုတ်မြို့နယ်'],
            ['township_abbreviation' => 'စတန', 'township_name' => 'စစ်တွေမြို့နယ်'],
            ['township_abbreviation' => 'ဘသတ', 'township_name' => 'ဘူးသီးတောင်မြို့နယ်'],
            ['township_abbreviation' => 'မတန', 'township_name' => 'မောင်တောမြို့နယ်'],
            ['township_abbreviation' => 'ကဖန', 'township_name' => 'ကျောက်ဖြူမြို့နယ်'],
            ['township_abbreviation' => 'သတန', 'township_name' => 'သံတွဲမြို့နယ်']
        ],
        12 => [
            ['township_abbreviation' => 'ဒဂရ', 'township_name' => 'ဒဂုံမြို့သစ်(အရှေ့ပိုင်း)'],
            ['township_abbreviation' => 'ဒဂမ', 'township_name' => 'ဒဂုံမြို့သစ်(မြောက်ပိုင်း)'],
            ['township_abbreviation' => 'ဒဂတ', 'township_name' => 'ဒဂုံမြို့သစ်(တောင်ပိုင်း)'],
            ['township_abbreviation' => 'အလမ', 'township_name' => 'အလုံမြို့နယ်'],
            ['township_abbreviation' => 'ဗဟန', 'township_name' => 'ဗဟန်းမြို့နယ်'],
            ['township_abbreviation' => 'ဗတထ', 'township_name' => 'ဗိုလ်တထောင်မြို့နယ်'],
            ['township_abbreviation' => 'ကကက', 'township_name' => 'ကိုကိုးကျွန်း'],
            ['township_abbreviation' => 'ဒဂဆ', 'township_name' => 'ဒဂုံမြို့သစ် (ဆိပ်ကမ်း)'],
            ['township_abbreviation' => 'ဒဂန', 'township_name' => 'ဒဂုံမြို့နယ်'],
            ['township_abbreviation' => 'ဒလန', 'township_name' => 'ဒလမြို့နယ်'],
            ['township_abbreviation' => 'ဒပန', 'township_name' => 'ဒေါပုံမြို့နယ်'],
            ['township_abbreviation' => 'လမန', 'township_name' => 'လှိုင်မြို့နယ်'],
            ['township_abbreviation' => 'လသယ', 'township_name' => 'လှိုင်သာယာမြို့နယ်'],
            ['township_abbreviation' => 'လကန', 'township_name' => 'လှည်းကူးမြို့နယ်'],
            ['township_abbreviation' => 'မဘန', 'township_name' => 'မှော်ဘီမြို့နယ်'],
            ['township_abbreviation' => 'ထတပ', 'township_name' => 'ထန်းတပင်မြို့နယ်'],
            ['township_abbreviation' => 'အစန', 'township_name' => 'အင်းစိန်မြို့နယ်'],
            ['township_abbreviation' => 'ကမရ', 'township_name' => 'ကမာရွတ်မြို့နယ်'],
            ['township_abbreviation' => 'ကမန', 'township_name' => 'ကော့မှူးမြို့နယ်'],
            ['township_abbreviation' => 'ခရန', 'township_name' => 'ခရမ်းမြို့နယ်'],
            ['township_abbreviation' => 'ကခက', 'township_name' => 'ကွမ်းခြံကုန်းမြို့နယ်'],
            ['township_abbreviation' => 'ကတတ', 'township_name' => 'ကျောက်တံတားမြို့နယ်'],
            ['township_abbreviation' => 'ကတန', 'township_name' => 'ကျောက်တန်းမြို့နယ်'],
            ['township_abbreviation' => 'ကမတ', 'township_name' => 'ကြည်မြင်တိုင်မြို့နယ်'],
            ['township_abbreviation' => 'လမတ', 'township_name' => 'လမ်းမတော်မြို့နယ်'],
            ['township_abbreviation' => 'လသန', 'township_name' => 'လသာမြို့နယ်'],
            ['township_abbreviation' => 'မရက', 'township_name' => 'မရမ်းကုန်းမြို့နယ်'],
            ['township_abbreviation' => 'မဂဒ', 'township_name' => 'မင်္ဂလာဒုံမြို့နယ်'],
            ['township_abbreviation' => 'ဥကမ', 'township_name' => 'မြောက်ဥက္ကလာပမြို့နယ်'],
            ['township_abbreviation' => 'ပဘတ', 'township_name' => 'ပန်းဘဲတန်းမြို့နယ်'],
            ['township_abbreviation' => 'ပဇတ', 'township_name' => 'ပုဇွန်တောင်မြို့နယ်'],
            ['township_abbreviation' => 'စခန', 'township_name' => 'စမ်းချောင်းမြို့နယ်'],
            ['township_abbreviation' => 'ဆကခ', 'township_name' => 'ဆိပ်ကြီးခနောင်တိုမြို့နယ်'],
            ['township_abbreviation' => 'ဆကန', 'township_name' => 'ဆိပ်ကမ်းမြို့နယ်'],
            ['township_abbreviation' => 'ရပသ', 'township_name' => 'ရွှေပြည်သာမြို့နယ်'],
            ['township_abbreviation' => 'ဥကတ', 'township_name' => 'တောင်ဥက္ကာပမြို့နယ်'],
            ['township_abbreviation' => 'တကန', 'township_name' => 'တိုက်ကြီးမြို့နယ်'],
            ['township_abbreviation' => 'တမန', 'township_name' => 'တာမွေမြို့နယ်'],
            ['township_abbreviation' => 'သကတ', 'township_name' => 'သာကေတမြို့နယ်'],
            ['township_abbreviation' => 'သလန', 'township_name' => 'သန်လျင်မြို့နယ်'],
            ['township_abbreviation' => 'သဃက', 'township_name' => 'သင်္ဃန်းကျွန်းမြို့နယ်'],
            ['township_abbreviation' => 'သခန', 'township_name' => 'သုံးခွမြို့နယ်'],
            ['township_abbreviation' => 'တတန', 'township_name' => 'တွံတေးမြို့နယ်'],
            ['township_abbreviation' => 'ရကန', 'township_name' => 'ရန်ကင်းမြို့နယ်'],
            ['township_abbreviation' => 'မဂတ', 'township_name' => 'မင်္ဂလာတောင်ညွှန့်မြို့နယ်'],
        ],
        13 => [
            ['township_abbreviation' => 'သပန', 'township_name' => 'သီပေါမြို့နယ်'],
            ['township_abbreviation' => 'ဟပန', 'township_name' => 'ဟိုပန်မြို့နယ်'],
            ['township_abbreviation' => 'သနန', 'township_name' => 'သိန်းနီမြို့နယ်'],
            ['township_abbreviation' => 'ဆဆန', 'township_name' => 'ဆီဆိုင်မြို့နယ်'],
            ['township_abbreviation' => 'ကလန', 'township_name' => 'ကလောမြို့နယ်'],
            ['township_abbreviation' => 'ဟပန', 'township_name' => 'ဟိုပုံးမြို့နယ်'],
            ['township_abbreviation' => 'ကတန', 'township_name' => 'ကျိုင်းတုံမြို့နယ်'],
            ['township_abbreviation' => 'ကကန', 'township_name' => 'ကုန်ကြမ်းမြို့နယ်'],
            ['township_abbreviation' => 'ကဟန', 'township_name' => 'ကွန်ဟိန်းမြို့နယ်'],
            ['township_abbreviation' => 'ကလန', 'township_name' => 'ကွန်လုံမြို့နယ်'],
            ['township_abbreviation' => 'ကခန', 'township_name' => 'ကွတ်ခိုင်မြို့နယ်'],
            ['township_abbreviation' => 'ကမန', 'township_name' => 'ကျောက်မဲမြို့နယ်'],
            ['township_abbreviation' => 'ကသန', 'township_name' => 'ကျေးသီးမြို့နယ်'],
            ['township_abbreviation' => 'လခန', 'township_name' => 'လင်းခေးမြို့နယ်'],
            ['township_abbreviation' => 'လရန', 'township_name' => 'လားရှိုးမြို့နယ်'],
            ['township_abbreviation' => 'လကန', 'township_name' => 'လောက်ကိုင်မြို့နယ်'],
            ['township_abbreviation' => 'လလန', 'township_name' => 'လွိုင်လင်မြို့နယ်'],
            ['township_abbreviation' => 'မဘန', 'township_name' => 'မဘိမ်းမြို့နယ်'],
            ['township_abbreviation' => 'မတန', 'township_name' => 'မန်တုံမြို့နယ်'],
            ['township_abbreviation' => 'မမန', 'township_name' => 'မက်မန်းမြို့နယ်'],
            ['township_abbreviation' => 'မဆန', 'township_name' => 'မိုင်းဆက်မြို့နယ်'],
            ['township_abbreviation' => 'မရန', 'township_name' => 'မိုင်းရှူးမြို့နယ်'],
            ['township_abbreviation' => 'မကန', 'township_name' => 'မိုင်းကိုင်မြို့နယ်'],
            ['township_abbreviation' => 'မဖန', 'township_name' => 'မိုင်းဖြတ်မြို့နယ်'],
            ['township_abbreviation' => 'မခန', 'township_name' => 'မိုင်းခတ်မြို့နယ်'],
            ['township_abbreviation' => 'မလန', 'township_name' => 'မိုင်းလားမြို့နယ်'],
            ['township_abbreviation' => 'မမန', 'township_name' => 'မိုးမိတ်မြို့နယ်'],
            ['township_abbreviation' => 'မနန', 'township_name' => 'မိုးနဲမြို့နယ်'],
            ['township_abbreviation' => 'မပန', 'township_name' => 'မိုင်းပန်မြို့နယ်'],
            ['township_abbreviation' => 'မပန', 'township_name' => 'မိုင်းပျဉ်းမြို့နယ်'],
            ['township_abbreviation' => 'မတန', 'township_name' => 'မိုင်းတုံမြို့နယ်'],
            ['township_abbreviation' => 'မရန', 'township_name' => 'မိုင်းရယ်မြို့နယ်'],
            ['township_abbreviation' => 'မယန', 'township_name' => 'မိုင်းယန်းမြို့နယ်'],
            ['township_abbreviation' => 'မယန', 'township_name' => 'မိုင်းယောင်းမြို့နယ်'],
            ['township_abbreviation' => 'မမန', 'township_name' => 'မောက်မန်မြို့နယ်'],
            ['township_abbreviation' => 'မဆန', 'township_name' => 'မူဆယ်မြို့နယ်'],
            ['township_abbreviation' => 'နခန', 'township_name' => 'နမ့်ခမ်းမြို့နယ်'],
            ['township_abbreviation' => 'နဆန', 'township_name' => 'နမ့်ဆန်မြို့နယ်'],
            ['township_abbreviation' => 'နစန', 'township_name' => 'နမ့်စန်မြို့နယ်'],
            ['township_abbreviation' => 'နမတ', 'township_name' => 'နမ္မတူမြို့နယ်'],
            ['township_abbreviation' => 'နဖန', 'township_name' => 'နားဖန်းမြို့နယ်'],
            ['township_abbreviation' => 'ညရန', 'township_name' => 'နောင်ချိုမြို့နယ်'],
            ['township_abbreviation' => 'ညရန', 'township_name' => 'ညောင်ရွှေမြို့နယ်'],
            ['township_abbreviation' => 'ပဆန', 'township_name' => 'ပန်ဆန်း/ပန်ခမ်းမြို့နယ်'],
            ['township_abbreviation' => 'ပဝန', 'township_name' => 'ပန်ဝိုင်မြို့နယ်'],
            ['township_abbreviation' => 'ဖခန', 'township_name' => 'ဖယ်ခုံမြို့နယ်'],
            ['township_abbreviation' => 'ပတယ', 'township_name' => 'ပင်းတယမြို့နယ်'],
            ['township_abbreviation' => 'ပလန', 'township_name' => 'ပင်းလောင်းမြို့နယ်'],
            ['township_abbreviation' => 'တခလ', 'township_name' => 'တာချီလိတ်မြို့နယ်'],
            ['township_abbreviation' => 'တယန', 'township_name' => 'တန့်ယန်းမြို့နယ်'],
            ['township_abbreviation' => 'တကန', 'township_name' => 'တောင်ကြီးမြို့နယ်'],
            ['township_abbreviation' => 'ရစန', 'township_name' => 'ရပ်စောက်မြို့နယ်'],
            ['township_abbreviation' => 'ရငန', 'township_name' => 'ရွာငံမြို့နယ်'],
            ['township_abbreviation' => 'မမန', 'township_name' => 'မိုင်းမောမြို့နယ်'],
            ['township_abbreviation' => 'လခန', 'township_name' => 'လဲချားမြို့နယ်'],
        ],
        14 => [ // 'ဧရာဝတီတိုင်း'
            ['township_abbreviation' => 'ပသန', 'township_name' => 'သာပေါင်းမြို့နယ်'],
            ['township_abbreviation' => 'ဟသတ', 'township_name' => 'ဟင်္သာတမြို့နယ်'],
            ['township_abbreviation' => 'မအန', 'township_name' => 'မြန်အောင်မြို့နယ်'],
            ['township_abbreviation' => 'မမန', 'township_name' => 'မြောင်းမြမြို့နယ်'],
            ['township_abbreviation' => 'ဖပန', 'township_name' => 'ဖျာပုံမြို့နယ်'],
            ['township_abbreviation' => 'လပတ', 'township_name' => 'လပွတ္တာမြို့နယ်'],
            ['township_abbreviation' => 'ကကထ', 'township_name' => 'ကန်ကြီးထောင့်မြို့နယ်'],
            ['township_abbreviation' => 'ငပတ', 'township_name' => 'ငပုတောမြို့နယ်'],
            ['township_abbreviation' => 'သပန', 'township_name' => 'ပုသိမ်မြို့နယ်'],
            ['township_abbreviation' => 'ကကန', 'township_name' => 'ကျောင်းကုန်းမြို့နယ်'],
            ['township_abbreviation' => 'ကပန', 'township_name' => 'ကျုံပျော်မြို့နယ်'],
            ['township_abbreviation' => 'ရကန', 'township_name' => 'ရေကြည်မြို့နယ်'],
            ['township_abbreviation' => 'ဇလန', 'township_name' => 'ဇလွန်မြို့နယ်'],
            ['township_abbreviation' => 'လမန', 'township_name' => 'လေးမျက်နှာမြို့နယ်'],
            ['township_abbreviation' => 'ကခန', 'township_name' => 'ကြံခင်းမြို့နယ်'],
            ['township_abbreviation' => 'အဂပ', 'township_name' => 'အင်္ဂပူမြို့နယ်'],
            ['township_abbreviation' => 'အမန', 'township_name' => 'အိမ်မဲမြို့နယ်'],
            ['township_abbreviation' => 'မအပ', 'township_name' => 'မအူပင်မြို့နယ်'], //??
            ['township_abbreviation' => 'ဝခမ', 'township_name' => 'ဝါးခယ်မမြို့နယ်'],
            ['township_abbreviation' => 'ပတန', 'township_name' => 'ပန်းတနော်မြို့နယ်'],
            ['township_abbreviation' => 'ညတန', 'township_name' => 'ညောင်တုန်းမြို့နယ်'],
            ['township_abbreviation' => 'ဓနဖ', 'township_name' => 'ဓနုဖြူမြို့နယ်'],
            ['township_abbreviation' => 'ဘကလ', 'township_name' => 'ဘိုကလေးမြို့နယ်'],
            ['township_abbreviation' => 'ကလန', 'township_name' => 'ကျိုက်လတ်မြို့နယ်'],
            ['township_abbreviation' => 'ဒဒရ', 'township_name' => 'ဒေးဒရဲမြို့နယ်'],
            ['township_abbreviation' => 'မမက', 'township_name' => 'မော်လမြိုင်ကျွန်းမြို့နယ်']
        ]
    ];


    public function run()
    {
        $this->showFeedback('Seeding townships for NRC states');
        $this->progressStart(count($this->states_with_townships));
        foreach ($this->states_with_townships as $state_id => $townships) {
            foreach ($townships as $township) {
                \Illuminate\Support\Facades\DB::table('nrc_townships')->insert([
                    'state_id' => $state_id,
                    'township_abbreviation' => $township['township_abbreviation'] ?? $township,
                    'township_name' => $township['township_name'] ?? null,
                    'created_at' => \Carbon\Carbon::now()
                ]);
            }
            $this->progressAdvance();
        }
        $this->progressFinish();

    }
}
