<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class Enrollment extends Model
{
    use LogsActivity;
    protected static $recordEvents = ['updated', 'deleted'];
    protected static $logName = 'student_detail';
    protected static $logAttributes = [
        'year',
        'major',
        'roll_no',
        'photo',
        'stipend',
        'boudoir',
        'current_address',
        'current_phone',
        'data'
    ];

    protected static $logOnlyDirty = true;

    protected $fillable = [
        'year',
        'major',
        'roll_no',
        'photo',
        'stipend',
        'boudoir',
        'current_address',
        'current_phone',
        'data',
    ];

    protected $casts = [
        'data' => 'array',
        'major' => 'array'
    ];

    public function student()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function acceptance()
    {
        return $this->hasOne(Acceptance::class);
    }

    public function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

}
